language: r
cache: packages
warnings_are_errors: true
sudo: required

apt_packages:
  - jags

r_packages:
  - covr
  - Luminescence
  - hexbin
  - rjags
  - ArchaeoPhases
  - R.rsp

## test different platforms
matrix:
  include:
  - os: linux
    r: release
    env: CACHE_NAME=JOB1
  - os: linux
    r: devel
    env: CACHE_NAME=JOB2
  - os: osx
    r: release
    before_install:
      - rm '/usr/local/bin/gfortran'
      - sudo chown -R travis /usr/local
      - brew update
      - brew install jags
      - brew install libssh2
      - curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
      - sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
    env: CACHE_NAME=JOB3

##create notifications
notifications:
  email:
    recipients:
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

##grep data from testthat
after_success:
- Rscript -e 'covr::codecov()'
