language: r
cache: packages
warnings_are_errors: true
sudo: required

apt_packages:
  - jags
  - libgdal1-dev
  - libproj-dev

r_packages:
  - devtools
  - covr
  - Luminescence
  - hexbin
  - rjags
  - ArchaeoPhases
  - R.rsp

## test different platforms
matrix:
  include:
  - os: linux
    r: oldrel
    env: CACHE_NAME=JOB1
  - os: linux
    r: release
    env: CACHE_NAME=JOB2
  - os: linux
    r: devel
    env: CACHE_NAME=JOB3
  - os: osx
    r: release
    before_install:
      - sudo chown -R travis /usr/local
      - sudo rm '/usr/local/include/c++'
      - sudo rm '/usr/local/bin/gfortran'
      - brew install gcc
      - brew install jags
      - brew install libssh2
    env: CACHE_NAME=JOB3

##create notifications
notifications:
  email:
    recipients:
      - sk@r-luminescence.de
      - gguerin@u-bordeaux-montaigne.fr
      - anne.philippe@univ-nantes.fr
    on_success: change
    on_failure: change

##grep data from testthat
after_success:
- Rscript -e 'covr::codecov()'
